server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: letsrock
    url: jdbc:mysql://localhost:3306/userdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
